version: '3'
services:
  pandora-helper:
    image: kylsky/pandora_helper_v2
    volumes:
      - db-data:/app/db
    environment:
      CLIENT_ID: ""                                   # 1.你的linux-do oauth client
      CLIENT_SECRET: ""                               # 2.你的linux-do oauth secret
      REDIRECT_URI: ""                                # 3.必填，你的应用地址（请填写公网地址）
      OAIFREE_PROXY: "https://new.oaifree.com"        # 4.默认oaifree，你可以填写你的代理地址
      FUCLAUDE_PROXY: "https://demo.fuclaude.com"     # 5.默认fuclaude，你可以填写你的fuclaude地址
      TZ: "Asia/Shanghai"
      ADMIN_NAME: "Admin"                             # 6.管理员用户名，建议填写你在linux-do的用户名，默认密码是123456
      CHAT_SITE: "https://next.yeelo.top"             # 7.填写你的ChatGPTNextWeb地址
      SMTP_ENABLE: true                               # 8.是否启用邮件提醒,true/false,如果是false，可以不配置下方邮件服务器信息
      SMTP_MAIL_HOST: "smtp.qq.com"                   # 9.邮件服务器地址
      SMTP_MAIL_PORT: 465                             # 10.邮件服务器端口
      SMTP_MAIL_USERNAME: "your_username"             # 11.邮件服务器用户名
      SMTP_MAIL_PASSWORD: "your_password"             # 12.邮件服务器密码
      MIRROR_ENABLE: true                             # 13.是否启用MIRROR镜像
      MIRROR_HOST: http://localhost:50002             # 14.填写你的mirror服务地址，由于该地址会直接在页面跳转，建议填写域名，避免局域网外无法访问/ip泄漏等问题
    ports:
      - "8181:8181"                                   # 15.如需修改端口，请修改第一个8181为你需要访问的服务器端口
    restart: always
  mirror:
    image: dairoot/chatgpt-gateway:latest
    environment:
      ENABLE_MIRROR_API: false
      PROXY_URL_POOL: ""                              # 16.选填，代理地址用逗号分隔,如：“http://username:password@ip:port,socks5://username:password@ip:port”
      REDIS_URL: redis://redis:6379/0
    ports:
      - "50002:8787"                                  # 17.如需修改端口，请修改第一个8181为你需要访问的服务器端口
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:16379:6379"
    volumes:
      - ./redis-data:/data                            # 18.指定宿主机的redis数据挂载目录
    command: ["redis-server","--appendonly","yes" ]
  cf5s:
    image: dairoot/cf5s:latest
    restart: always
    environment:
      CHATGPT_GATEWAY_URL: "http://mirror:8787"
      #PROXY_URL_POOL: ""                             # 19.选填，代理地址用逗号分隔,如：“http://username@password@ip:port,socks5://username@password@ip:port”

  # 更多部署细节请参考：https://github.com/trueai-org/midjourney-proxy
  mjopen:
    image: registry.cn-guangzhou.aliyuncs.com/trueai-org/midjourney-proxy
    container_name: mjopen
    restart: always
    ports:
      - "8086:8080"
    user: "root"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
      - ./attachments:/app/wwwroot/attachments:rw
      - ./ephemeral-attachments:/app/wwwroot/ephemeral-attachments:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/db                                # 18.指定宿主机的数据库挂载目录，必须使用绝对路径
