version: '3'
services:
  pandora-helper:
    image: kylsky/pandora_helper_v2
    volumes:
      - db-data:/app/db
    environment:
      CLIENT_ID: ""                                   # 1.你的linux-do oauth client
      CLIENT_SECRET: ""                               # 2.你的linux-do oauth secret
      REDIRECT_URI: ""                                # 3.必填，你的应用地址
      OAIFREE_PROXY: "https://new.oaifree.com"        # 4.默认oaifree，你可以填写你的代理地址
      FUCLAUDE_PROXY: "https://demo.fuclaude.com"     # 5.默认fuclaude，你可以填写你的fuclaude地址
      TZ: "Asia/Shanghai"
      ADMIN_NAME: "Admin"                             # 6.管理员用户名，建议填写你在linux-do的用户名，默认密码是123456
      CHAT_SITE: "https://next.yeelo.top"             # 7.填写你的ChatGPTNextWeb地址
      SMTP_ENABLE: true                               # 8.是否启用邮件提醒,true/false,如果是false，可以不配置下方邮件服务器信息
      SMTP_MAIL_HOST: "smtp.qq.com"                   # 9.邮件服务器地址
      SMTP_MAIL_PORT: 465                             # 10.邮件服务器端口
      SMTP_MAIL_USERNAME: "your_username"             # 11.邮件服务器用户名
      SMTP_MAIL_PASSWORD: "your_password"             # 12.邮件服务器密码
    ports:
      - "8181:8181"                                   # 13.如需修改端口，请修改第一个8181为你需要访问的服务器端口
    restart: always

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/db                # 8.指定宿主机的数据库挂载目录，必须使用绝对路径
