spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/app/db/data.db
    username:
    password: