server:
  port: ${SERVER_PORT:8181}

spring:
  mail:
    enable: ${SMTP_ENABLE:false}
    host: ${SMTP_MAIL_HOST:smtp.qq.com}
    port: ${SMTP_MAIL_PORT:465}
    username: ${SMTP_MAIL_USERNAME:0}
    password: ${SMTP_MAIL_PASSWORD:0}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socket:
            factory:
              class: javax.net.ssl.SSLSocketFactory

linux-do:
  fuclaude: ${FUCLAUDE_URL:https://demo.fuclaude.com}
  oaifree:
    auth-api: ${OAIFREE_AUTH_API:https://new.oaifree.com}
    token-api: ${OAIFREE_TOKEN_API:https://new.oaifree.com/api/auth/oauth_token}
  oauth2:
    client:
      registration:
        client-id: ${CLIENT_ID:test}
        client-secret: ${CLIENT_SECRET:test}
        redirect-uri: ${REDIRECT_URI:http://localhost:8181}
        authorization-grant-type: authorization_code
        scope: read,write
      provider:
        authorization-uri: ${OAUTH_AUTH_URI:https://connect.linux.do/oauth2/authorize}
        token-uri: ${OAUTH_TOKEN_URI:https://connect.linux.do/oauth2/token}
        user-info-uri: ${OAUTH_USER_INFO_URI:https://connect.linux.do/api/user}
        user-name-attribute: id

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

admin-name: ${ADMIN_NAME:admin}
chat_site: ${CHAT_SITE:https://next.yeelo.top}
tokenProxy: ${TOKEN_PROXY:http://mysh.yeelo.fun：16666}
task:
  refresh: ${REFRESH_TASK_EXPRESSION:0 0 2 * * ?}  # 使用环境变量，冒号后面是默认值
midjourney:
    url: ${MJ_URL:https://discord.com}
    key: ${MJ_KEY:}
    enable: ${MJ_ENABLE:false}


mirror:
  enable: ${MIRROR_ENABLE:true}
  host: ${MIRROR_HOST:http://127.0.0.1:50002}
  password: ${MIRROR_PASSWORD:-}