server:
  port: ${SERVER_PORT:8181}

spring:
  profiles:
    include:
        - ${DB_TYPE:sqlite}  # 默认使用sqlite，可通过环境变量DB_TYPE切换为mysql
        - prod
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml