server:
  port: 8181

linux-do:
  fuclaude: ${FUCLAUDE_PROXY:https://demo.fuclaude.com}
  oaifree:
    auth-api: ${OAIFREE_PROXY:https://new.oaifree.com}
    token-api: https://new.oaifree.com/api/auth/oauth_token
  oauth2:
    enable: ${OAUTH2_ENABLE:true}
    client:
      registration:
        client-id: ${CLIENT_ID:0}
        client-secret: ${CLIENT_SECRET:0}
        redirect-uri: ${REDIRECT_URI:0}
        authorization-grant-type: authorization_code
        scope: read,write
      provider:
        authorization-uri: https://connect.linux.do/oauth2/authorize
        token-uri: https://connect.linux.do/oauth2/token
        user-info-uri: https://connect.linux.do/api/user
        user-name-attribute: id
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  mail:
    enable: ${SMTP_ENABLE:false}
    host: ${SMTP_MAIL_HOST:smtp.qq.com}
    port: ${SMTP_MAIL_PORT:465}
    username: ${SMTP_MAIL_USERNAME:0}
    password: ${SMTP_MAIL_PASSWORD:0}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socket:
            factory:
              class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

admin-name: ${ADMIN_NAME:admin}
chat_site: ${CHAT_SITE:https://next.yeelo.top}
task:
  refresh: ${REFRESH_TASK_EXPRESSION:0 0 2 * * ?}  # 使用环境变量，冒号后面是默认值


mirror:
  enable: ${MIRROR_ENABLE:true}
  host: ${MIRROR_HOST:http://127.0.0.1:50002}
  password: ${MIRROR_PASSWORD:-}